blank_issues_enabled: false
contact_links:
  - name: ğŸ™ Need Help?
    url: https://discord.gg/thirdweb
    about: Join the official thirdweb discord server and mention me (@waren).
  - name: ğŸ“š Learn More!
    url: https://github.com/HashLips/hashlips_art_engine
    about: Learn more about the art engine.